### ISSUE TITLE
OS-js

### ISSUE THREAD

**Issue by formula1** [Silk-GUI/Silk#24]
https://github.com/os-js/OS.js
http://os.js.org/doc/

Looks like a cool project. Much further along as well. I imagine that NodeOS will likely be using this as its defacto window/application manager. Doesn't mean Silk can't continue, just means that it has a standard it must be better than or find a nitch

**Comment by zodern** [comment]
It does work nice. Though there is a few places we could do better.

 One is community apps. Apps that are created for it won't work outside of OS.js, except if it is a chrome app. If we allow silk apps to also run standalone using  `npm start` or run as a desktop program (using electron, nw.js or brackets shell) then there would be more incentive to create apps that are compatible with Silk.

Also, I want to explore the possibility of using Silk to access a computer remotely instead of using ssh.

**Comment by formula1** [comment]
One thing we can do is allow for [commander](https://github.com/tj/commander.js?utm_source=jobboleblog) to be shimmed.

Picture this
- We run the bin in the browser
- We shim commander
  - We allow the user to choose their form (based off git style sub commands)
- As the Forms are compiled, the options are added

The difficulties with this would probably be as follows
- We would need to ensure that commander is Type Strict
  - When providing inputs
    - Files can be from local or from server
    - Inputs may be a number, string and etc
    - Some handle streams (if ffmpeg ever gets rewritten in node, which it likely won't, at times it needs to expect a stream input)
-

**Comment by zodern** [comment]
There is [this project](https://github.com/UniversalGUI/UGUI) which allows developers to manually convert their cli apps to nw.js apps.

It would be great if your idea worked, but on the browser we would be lacking many globals, and how would we handle `require` when we run the command's bin?  I might not understand your idea.
Another idea is running `theCommand --help` and parse the output.
